id: 1
name: 笔趣阁22
base_url: https://www.22biqu.com
charset: utf-8
rate_limit: { rps: 2, burst: 4 }
retries: 3
timeout_seconds: 15
proxy: ""

headers:
  Accept-Language: "zh-CN,zh;q=0.9"

search:
  path: /ss
  param: searchkey
  item_selector: ".txt-list li:nth-child(n+2)"
  title_selector: ".s2"
  author_selector: ".s4"
  link_selector: "a"
  link_attr: href
  update_selector: ".s5"
  category_selector: ".s1"

chapters:
  list_selector: "body > div.container > div.row.row-section > div.layout.layout-col1 > div:nth-child(4) > ul li"
  title_selector: "a"
  url_selector: "a"
  url_attr: href
  pagination:
    next_selector: "body > div.container > div.row.row-section > div.layout.layout-col1 > div.index-container > a:nth-child(3)"   # 例如 “下一页”按钮
    next_attr: "href"               # 默认 href，可省略
    max_pages: 30                   # 安全上限
    stop_on_same: true              # 如下一页没有新增则停止

content:
  content_selector: ".content"
